### bad auth not json
POST http://127.0.0.1:8080/auth
Content-Type: application/json

fwefew

### bad auth
POST http://127.0.0.1:8080/auth
Content-Type: application/json

{ "username": "fweef","password":"chopa" }

### OPTIONS
OPTIONS http://127.0.0.1:8080/auth
Content-Type: application/json

{ "username": "fweef","password":"chopa" }

### success auth
POST http://127.0.0.1:8080/auth
Content-Type: application/json

{ "username": "admin","password":"admin" }


### dash
GET http://127.0.0.1:8080/dash
Content-Type: application/json

### stats
GET http://127.0.0.1:8080/stats
Content-Type: application/json

### stats items
GET http://127.0.0.1:8080/stats-items
Content-Type: application/json


### logout
POST http://127.0.0.1:8080/logout
Content-Type: application/json